name: Deploy CoreLord Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install only at repo root (where package.json is)
      - name: Install deps
        run: npm ci

      # Build if you ever add one (noop otherwise)
      - name: Build (noop if not present)
        run: npm run build --if-present

      # Create a small deploy zip (exclude CI metadata)
      - name: Create deploy zip
        run: |
          zip -r deploy.zip . \
            -x ".git/*" ".github/*" "node_modules/*"

      - name: Azure login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App (corelord-backend)
        uses: azure/webapps-deploy@v3
        with:
          app-name: corelord-backend
          package: ./deploy.zip
